# Generated by Django 6.0.7 on 2026-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='docente')),
            ],
        ),
    ]
