# Generated by Django 6.0.7 on 2026-07-12 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(help_text='Numero de cedula (10 digitos).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cedula debe contener exactamente 10 digitos numericos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
    ]
