estudiantes = [
  {
    id: 1,
    "nombre": "Víctor Roberto Bravo Torres",
    "carrera": "Ingeniería en Tecnologías de la Información",
    "nivel": "6to Nivel",
    "paralelo": "C1",
    "correo": "vbravot@unemi.edu.ec",
    "imagen": "../../../media/estudiante/vbravo.jpeg",
  },
  {
    id: 2,
    "nombre": "Víctor Hugo Herrera Hernández",
    "carrera": "Ingeniería en Tecnologías de la Información",
    "nivel": "6to Nivel",
    "paralelo": "C1",
    "correo": "vherrerah@unemi.edu.ec",
    "imagen": "../../../media/estudiante/vherrera.jpeg",
  },
  {
    id: 3,
    "nombre": "César Luis Hidalgo Mariño",
    "carrera": "Ingeniería en Tecnologías de la Información",
    "nivel": "6to Nivel",
    "paralelo": "C1",
    "correo": "chidalgom3@unemi.edu.ec",
    "imagen": "../../../media/estudiante/chidalgo.jpg",
  },
  {
    id: 4,
    "nombre": "Fabricio Alexander Sánchez Vinces",
    "carrera": "Ingeniería en Tecnologías de la Información",
    "nivel": "6to Nivel",
    "paralelo": "C1",
    "correo": "fsanchezv9@unemi.edu.ec",
    "imagen": "../../../media/estudiante/fsanchez.jpeg",
  },
  {
    id: 5,
    "nombre": "Pedro Gonzalo Bravo Zambrano",
    "carrera": "Ingeniería en Tecnologías de la Información",
    "nivel": "6to Nivel",
    "paralelo": "C1",
    "correo": "pbravoz@unemi.edu.ec",
    "imagen": "../../../media/estudiante/pbravo.jpeg",
  },
];