# Generated by Django 6.0.7 on 2026-07-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('nivel', models.CharField(max_length=20)),
                ('horas_semanales', models.IntegerField()),
                ('jornada', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
        ),
    ]
