# Generated by Django 6.0.7 on 2026-07-12 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('docente', '0002_alter_docente_cedula_alter_docente_tipo_sangre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='docente.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='jornada',
            field=models.CharField(choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(help_text='Nivel de la malla curricular (1 a 10).', max_length=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
