# Generated by Django 6.0.7 on 2026-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_creditos_alter_curso_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horas_semanales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(max_length=20),
        ),
    ]
