# Generated by Django 6.0.7 on 2026-07-14 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_curso_creditos_alter_curso_horas_semanales_and_more'),
    ]

    def migrate_nivel_to_int(apps, schema_editor):
        Curso = apps.get_model('curso', 'Curso')
        nivel_map = {
            'primero': 1,
            'primer': 1,
            '1': 1,
            'segundo': 2,
            '2': 2,
            'tercero': 3,
            '3': 3,
            'cuarto': 4,
            '4': 4,
            'quinto': 5,
            '5': 5,
            'sexto': 6,
            '6': 6,
            'septimo': 7,
            'séptimo': 7,
            '7': 7,
            'octavo': 8,
            '8': 8,
            'noveno': 9,
            '9': 9,
            'decimo': 10,
            'décimo': 10,
            '10': 10,
        }

        for curso in Curso.objects.all():
            valor_nivel = str(curso.nivel).strip().lower()
            if valor_nivel in nivel_map:
                curso.nivel = nivel_map[valor_nivel]
                curso.save(update_fields=['nivel'])

    operations = [
        migrations.RunPython(migrate_nivel_to_int, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5'), (6, 'Nivel 6'), (7, 'Nivel 7'), (8, 'Nivel 8'), (9, 'Nivel 9'), (10, 'Nivel 10')], help_text='Nivel de la malla curricular (1 a 10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
